### ISSUE TITLE
Chmod segmentation fault

### ISSUE THREAD

**Issue by Stargirl-chan** [cheusov/nbase#10]
Hello,

during building of version 9.1.0.2 I noticed that the chmod utility simply segfaults when trying to change permissions.

The following is printed on terminal:
```
./chmod/chmod 0755 /home/star/test.txt
fish: Job 1, './chmod/chmod 0755 /home/star/t…' terminated by signal SIGSEGV (Address boundary error)
```
In dmesg it prints the following:
```
traps: chmod[11781] general protection fault ip:202865 sp:7fff0a10a690 error:0 in chmod[202000+1000]
traps: chmod[12313] general protection fault ip:202865 sp:7ffe611463b0 error:0 in chmod[202000+1000]
```

I went ahead and build a debug version of chmod, the following code seems to fail according to lldb
```
(lldb) run 0755 /home/star/test_chmod.txt
Process 26055 launched: '/home/star/sources/nbase/chmod/chmod' (x86_64)
Process 26055 stopped
* thread #1, name = 'chmod', stop reason = signal SIGSEGV: invalid address (fault address: 0x0)
    frame #0: 0x0000000000202865 chmod`main(argc=2, argv=0x00007fffffffe738) at chmod.c:222:40
   219 				break;
   220 			}
   221 			if ((*change_mode)(p->fts_accpath,
-> 222 			    set ? getmode(set, p->fts_statp->st_mode) : mval)
   223 			    && !fflag) {
   224 				warn("%s", p->fts_path);
   225 				rval = 1;
```
`st_mode` seems to not be initialized?
```
(lldb) frame variable mval
(mode_t) mval = 0
(lldb) frame variable p
(FTSENT *) p = 0x00000000002077a0
(lldb) frame variable p->fts_statp
(stat *) p->fts_statp = 0x6d68635f74736574
(lldb) frame variable p->fts_statp->st_mode
(__mode_t) p->fts_statp->st_mode = <read memory from 0x6d68635f7473658c failed (0 of 4 bytes read)>

(lldb)
```
   
   Compiler: clang
   OS: Void Linux x86_64
   CFLAGS are not set

**Comment by cheusov** [comment]
Thanks for the report! Void Linux is musl-based. Right?

**Comment by cheusov** [comment]
Hm. I'll try to reproduce it. Thanks!

**Comment by Stargirl-chan** [comment]
I found out the problem was on my end.
During compilation it wrongly pulled in a conflicting `fts.h` header for an alternative fts implementation, because of something I did earlier, but it did not link to the library that provides said implementation.

This was entirely accidental, I'm sorry.
