### ISSUE TITLE
Segfault in nbls

### ISSUE THREAD

**Issue by dfandrich** [cheusov/nbase#11]
Running `nbls -l` results in a segfault.

```
Program received signal SIGSEGV, Segmentation fault.
0x00007f32ec98b5c0 in getbsize () from /lib64/libbsd.so.0
(gdb) bt
#0  0x00007f32ec98b5c0 in getbsize () from /lib64/libbsd.so.0
#1  0x000055dd832bd83e in ls_main ()
#2  0x00007f32ec7a61f0 in __libc_start_call_main () from /lib64/libc.so.6
#3  0x00007f32ec7a62b9 in __libc_start_main_impl () from /lib64/libc.so.6
#4  0x000055dd832ba575 in _start ()
```
Tested in a Docker container on x86_64 with nbase-ls-9.3.0.1-55.13

**Comment by dfandrich** [comment]
For completeness, this was in the opensuse/tumbleweed container with libbsd0-0.11.7-2.6.x86_64 on a Linux 6.6.37 kernel.

**Comment by cheusov** [comment]
The problem here was that getbsize(3) provided by libbsd is not compatible with NetBSD's getbsize(3).
libbsd's getbsize(3) doesn't accept NULL as headerlenp.

I've just fixed the problem.

Thanks for pointing out!
