### ISSUE TITLE
nbtail fails to operate

### ISSUE THREAD

**Issue by dfandrich** [cheusov/nbase#12]
Running `nbtail` results in:
```
kevent is not supported
```
as does just about any other invocation of nbtail I tried (e.g. `nbtail -1 /etc/os-release`) and no other output is generated.

Tested in a Docker container on x86_64 with nbase-ls-9.3.0.1-55.13 on a Linux 6.6.37 kernel.

**Comment by cheusov** [comment]
Partially fixed in branch "master". "tail -f" is not supported on Linux and some other non-BSD systems.
