### ISSUE TITLE
Building on musl libc (sigsetmask et al missing)

### ISSUE THREAD

**Issue by staalmannen** [cheusov/nbase#4]
In contrast to glibc, musl is not having the "legacy" BSD functions and only POSIX sigprocmask.
Would it be possible to translate those functions when missing?

**Comment by cheusov** [comment]
yes

**Comment by staalmannen** [comment]
I could get past this issue by making a fake wrapper signal.h. 

`#ifndef _HACK_BSD_SIGNAL
#define _HACK_BSD_SIGNAL 1

#include "/usr/include/signal.h"
#define sigsetmask(x) sigprocmask(SIG_SETMASK,x,NULL)
#define sigblock(x) sigprocmask(SIG_BLOCK,x,NULL)
#define sigpause(x) sigsuspend(x)"
# define sigmask(x) \
  (((unsigned long int) 1) << (((x) - 1) % (8 * sizeof (unsigned long int))))

#endif`

I am not sure if this is the correct solution but it was what I could come up with after reading/searching for these functions. Is there a better way to "inject" custom definitions in this build system?

I still encounter other issues further downstream in the compilation but one problem at a time :) and if I figure out a way to more easily fix includes and definitions by a single "hack" header or similar, it will make the rest of the compilation easier.

Background: Why musl?
I am currently trying to assemble a custom Linux OS "Aalbus" (LLVM/clang/libc++, musl, [netbsd-curses, gettext-tiny, libnl-tiny from Sabotage Linux], mksh, pkgsrc, ...). Currently it is running on suckless.org sbase+ubase but I would love to move over to nbase+ubase instead as standard unix utilities.

A fun observation : to build nbase with netbsd-curses, I have to pass the variable 
HAVE_HEADER.curses_h=1 to bmake.

**Comment by cheusov** [comment]
Recently I fixed a lot of problems on Linux/musl. Please check again latest nbase.

**Comment by cheusov** [comment]
I assume this issue has been already fixed in 7.0.0.5 and 7.0.0.6. If it is not, feel free to reopen the issue or create a new one. Thank you for pointing out!
