### ISSUE TITLE
A bug with mv going missing during mkcmake install

### ISSUE THREAD

**Issue by staalmannen** [cheusov/nbase#5]
Hi.

I am using nbase and suckless ubase as core userland tools in my experimental Linux distribution Aalbus linux:
https://github.com/Aalbus-linux/Aalbus

As I updated nbase from inside Aalbus I encountered a bug where /bin/mv was removed before the new one was installed which made mkcmake install halt/fail after mv. The solution was easy (just copy mv to /usr/bin), which made mkcmake install work for all utilities.

**Comment by cheusov** [comment]
This happened, because you use mkc_install(1) shell script as a default for INSTALL vartiable in mk-configure. mkc_install uses mv(1). Solution for you is to use install(1) executable (it is written in C) instead of mkc_install(1) provided with mk-configure.

**Comment by cheusov** [comment]
Also see 965dcba commit in mk-configure.
Thanks for pointing out!
