### ISSUE TITLE
chmod invalid argument

### ISSUE THREAD

**Issue by Stargirl-chan** [cheusov/nbase#6]
Hello,

I recently build version 9.1.0.0 of nbase on Linux and encountered a bug with the `chmod` utility.
Trying to set the sticky bit will fail with the following error message: `chmod: Cannot set file mode '1755': Invalid argument`

However setting setuid and setgid works without problems.
This issue also occurs with the 7.0.0.7 version in pkgsrc.

**Comment by cheusov** [comment]
Fixed in e661edb6202d92d73579836c547cf0a440206812.
Thanks a lot for the report!
