### ISSUE TITLE
sort: setrlimit: Invalid argument

### ISSUE THREAD

**Issue by grylem** [cheusov/nbase#8]
Привет,
printf "%s\n" 3 2 1 | sort
sort: setrlimit: Invalid argument

**Comment by cheusov** [comment]
Could you please add some OS details? I cannot reproduce this issue.
It would be nice to see results for the following commands:
uname -srm
ldd ./sort
ulimit -a
strace sort 2>&1 | grep setrlimit (strace on Linux or alternatives on *BSD and macOS)

**Comment by grylem** [comment]
macOS
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 256
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 709
virtual memory          (kbytes, -v) unlimited

sort: setrlimit: Invalid argument
setrlimit(0x1008, 0x7FFEE285FA30, 0x0)		 = -1 Err#22

если собрать из NetBSD, а не nbase ошибка такая же, но при изменении RLIMIT_NOFILE на RLIMIT_DATA как в версии от OpenBSD все работает.

**Comment by cheusov** [comment]
> Привет, printf "%s\n" 3 2 1 | sort sort: setrlimit: Invalid argument

Исправил.  Проверяй в последнем master.
P.S. На Darwin-21.6.0 эта проблема не воспроизводится. Воспроизводится только на старых macOS.

**Comment by cheusov** [comment]
Fixed
